### ISSUE TITLE
getting error message when training

### ISSUE THREAD

**Issue by anjanatiha** [CogComp/ZeroShotWiki#1]
--:/shared/tiha/code_review/ZeroShotWiki> CUDA_VISIBLE_DEVICES=1 python src/train_wiki_entailment.py --data_file data/data/wikipedia/tokenized_wiki.txt --cate_file data/data/wikipedia/page2content_cate.json --save_dir "model2"
07/26/2022 16:40:32 - WARNING - transformers.modeling_utils -   Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
07/26/2022 16:40:32 - WARNING - transformers.modeling_utils -   Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "src/train_wiki_entailment.py", line 451, in <module>
    main()
  File "src/train_wiki_entailment.py", line 351, in main
    if os.path.exists(train_loader_file):
  File "/shared/tiha/miniconda3/envs/zsw/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by dht2345** [comment]
Resolved. https://github.com/CogComp/ZeroShotWiki/commit/74149d3842e07270b980f2bda570f3934de28481
