### ISSUE TITLE
Trainning stops after a while

### ISSUE THREAD

**Issue by anjanatiha** [CogComp/ZeroShotWiki#2]
The training script stops at 3% each time. 
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/22654200/181626761-dd291a9c-b320-46f0-bda8-680dd19ac61a.png">

**Comment by dht2345** [comment]
This is expected as the number of training steps is defaulted to 1500. Use larger value if you want to train longer.

**Comment by anjanatiha** [comment]
Should we keep the check to limit the steps?
